// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WorkshopApi.Contexts;

#nullable disable

namespace WorkshopApi.Migrations
{
    [DbContext(typeof(WorkshopContext))]
    [Migration("20240303032729_finished-pk")]
    partial class finishedpk
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("WorkshopApi.Entities.Collaborator", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Collaborators");
                });

            modelBuilder.Entity("WorkshopApi.Entities.CollaboratorWorkshop", b =>
                {
                    b.Property<Guid>("CollaboratorId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("WorkshopId")
                        .HasColumnType("char(36)");

                    b.HasKey("CollaboratorId", "WorkshopId");

                    b.HasIndex("WorkshopId");

                    b.ToTable("CollaboratorWorkshop");
                });

            modelBuilder.Entity("WorkshopApi.Entities.Workshop", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Workshop");
                });

            modelBuilder.Entity("WorkshopApi.Entities.CollaboratorWorkshop", b =>
                {
                    b.HasOne("WorkshopApi.Entities.Collaborator", "Collaborator")
                        .WithMany("CollaboratorWorkshops")
                        .HasForeignKey("CollaboratorId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("WorkshopApi.Entities.Workshop", "Workshop")
                        .WithMany("CollaboratorWorkshops")
                        .HasForeignKey("WorkshopId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Collaborator");

                    b.Navigation("Workshop");
                });

            modelBuilder.Entity("WorkshopApi.Entities.Collaborator", b =>
                {
                    b.Navigation("CollaboratorWorkshops");
                });

            modelBuilder.Entity("WorkshopApi.Entities.Workshop", b =>
                {
                    b.Navigation("CollaboratorWorkshops");
                });
#pragma warning restore 612, 618
        }
    }
}
